# Generated by Django 4.1.4 on 2023-01-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(blank=True, max_length=150)),
                ('problem_description', models.TextField(blank=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'In work'), (2, 'Done')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
